### ISSUE TITLE
How should I change the position of Term?

### ISSUE THREAD

**Issue by TillLindemann** [vimlab/split-term.vim#13]
when I use 10Term ,it will call a term on the top of my code,it looks weird and uncomfortable,how should I change that?

**Comment by mklabs** [comment]
Hi,

I don't know what 10Term is. We can change that by diving into split-term code. I know it's not perfect and have quite a few things I'd like to do related to that.

Do not hesistate to open another issue if you'd like to talk a bit more on this subject.

Quick note: I'm offline for the next two weeks.

**Comment by mklabs** [comment]
@TillLindemann You can maybe try `:VTerm`, V for vertical.

**Comment by TillLindemann** [comment]
sorry for the late reply, I fixed it by adding the "set splitbelow" in the vimrc or init.vim(for neovim),everything now works fine ,thank you for the great plugin!

**Comment by mklabs** [comment]
Happy to hear that you figured it out, sadly I couldn't fix it myself. There's a lot of things I'd like to add, currently working on onivim and I pointed out some painful points. Thanks for thx ;)
