### ISSUE TITLE
Key maps for mode change from terminal panes and pane navigatoin

### ISSUE THREAD

**Issue by ootoovak** [vimlab/split-term.vim#2]
In the newest Neovim.app (HEAD from today) the commands you had in this plug-in were not working for me. I copied the following from the Neovim terminal docs into my `.vimrc` and these work. Not sure if the API has changed since this plugin was created or if I am just missing something but thought I would pass it on.

```
tnoremap <Esc> <C-\><C-n>

tnoremap <A-h> <C-\><C-n><C-w>h
tnoremap <A-j> <C-\><C-n><C-w>j
tnoremap <A-k> <C-\><C-n><C-w>k
tnoremap <A-l> <C-\><C-n><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l
```

**Comment by mklabs** [comment]
Thanks @ootoovak I need to check.

**Comment by anilanar** [comment]
The mappings take effect only for the terminal buffer that is created with `:Term` or `:VTerm`, would that be why you thought it is broken in Neovim.app?

**Comment by yangmillstheory** [comment]
This is broken for me:

![image](https://user-images.githubusercontent.com/2729079/27258153-be6ed398-53a7-11e7-9fe1-569260a0500a.png)
F

**Comment by mklabs** [comment]
Hi guys, I'm going to close this issue, as it a bit old and I didn't encounter any issue, at least on my setup.

Feel free to re-open if you feel like it's still valid.
