### ISSUE TITLE
Option to disable [process exited as 0] in the end

### ISSUE THREAD

**Issue by bobbbay** [vimlab/split-term.vim#21]
Pretty self explanatory, the extra enter is super annoying. Is it possible to get rid of this?

**Comment by mtshrmn** [comment]
Hey I just stumbled upon your issue by chance. This isn't an issue with split-term, its a thing with neovim's terminal. 
I found a solution that works for me and I think you should check out.
```vim
augroup terminal_settings
    autocmd!

    autocmd BufWinEnter,WinEnter term://* startinsert
    autocmd BufLeave term://* stopinsert

    " Ignore various filetypes as those will close terminal automatically
    " Ignore fzf, ranger, coc
    autocmd TermClose term://*
          \ if (expand('<afile>') !~ "fzf") && (expand('<afile>') !~ "ranger") && (expand('<afile>') !~ "coc") |
          \   call nvim_input('<CR>')  |
          \ endif
  augroup END
```

full credit goes to [u/mars26](https://www.reddit.com/r/neovim/comments/cger8p/how_quickly_close_a_terminal_buffer/eupal7q/)

**Comment by bobbbay** [comment]
That is beautiful! Although I don't use splitterm anymore, this is super useful. Thank you to both yourself and u/mars26!
