### ISSUE TITLE
Key mappings don't work once I'm back in nvim

### ISSUE THREAD

**Issue by bobbbay** [vimlab/split-term.vim#22]
If I `:Term`, then `Alt+K`, I'll have a terminal at the bottom that I can't get back to. `Alt+J` doesn't get me back to the terminal, just goes a line down. Same for all other mappings that are in this. How exactly are we supposed to get back? Cheers!

**Comment by fridgelord** [comment]
Provided mappings work only in the terminal window. So, to go back from "standard" window you to need to set for example 
```nnoremap <A-j> <C-w><C-j>```
and similar for other movements in your `init.vim` file.

**Comment by bobbbay** [comment]
Awesome, thanks!
