### ISSUE TITLE
Question: how have you configured the buffer display bar at the top of the demo gif.

### ISSUE THREAD

**Issue by piersy** [vimlab/split-term.vim#4]
Hi apologies for abusing the issue system, but git has no means for private messaging. 

I was wondering how you are achieving that cool looking top-bar display showing open files along with icons and a buffers section on the right?

Thanks in advance

Piers

**Comment by mklabs** [comment]
Hi Piers,

First off, sorry for the very late response. I don't use this setup anymore (using onivim) but I believe this achieved with vim-airline (https://github.com/vim-airline/vim-airline#smarter-tab-line)

**Comment by piersy** [comment]
@mklabs Well thanks for getting back to me, however late :) Onivim looks cool! I'll check it out.

**Comment by mklabs** [comment]
It is really cool indeed ;) I cannot recommend it enough.
